SELECT
    Trip.T_DEPART,
    ROUTE.ROU_DESC,
    TRIP.T_TRA_ID,
    TRAVELLER.TRA_NAME AS Traveller,
    TRIP.T_LEADER,
    LEADER.TRA_NAME AS Leader
FROM TRIP
JOIN TRAVELLER ON TRIP.T_TRA_ID = TRAVELLER.TRA_ID
JOIN TRAVELLER AS LEADER ON TRIP.T_LEADER = LEADER.TRA_ID
JOIN ROUTE ON TRIP.T_ROU_ID = ROUTE.ROU_ID
WHERE LEADER.TRA_NAME = 'Wilfred Pong'
ORDER BY TRIP.T_DEPART;